name: GitHub Bot Proxy

on:
  # Watch for changes on PR reviews
  pull_request_review:
    types: [submitted, edited, dismissed]

  # Watch for any completed run on current workflow (loop)
  workflow_run:
    workflows: [GitHub Bot Proxy]
    types: [completed]

jobs:
  save-pr-number:
    name: Persist PR number
    if: github.event.workflow_run.event == 'pull_request_review'
    runs-on: ubuntu-latest

    steps:
      - name: Write PR number to a file
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          mkdir -p ./persist
          echo $PR_NUMBER > ./persist/pr-number

      - name: Upload it as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-number
          path: persist/

  run-github-bot:
    name: Run Bot workflow
    if: github.event.workflow_run.event == 'workflow_run'
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Download artifact from previous run
        uses: actions/download-artifact@v4
        with:
          name: pr-number
          path: persist

      - name: Send workflow_dispatch event to Github Bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run bot.yml -f "pull-request-list=$(cat persist/pr-number)"
