name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Fail but continue
        id: download
        continue-on-error: true
        run: exit 1

      - name: Ignore if failed
        if: steps.download.outcome == 'success'
        run: echo "OK"
